stages:
  - manage-vm
  - docker-base
  - build
  - deploy

build-Virtual-Machine-omnetpp:
  stage: manage-vm
  
  script:
    # Attempt to cleanup any pre-existing VM
    - VBoxManage controlvm "omnetpp-vm" poweroff || true
    - VBoxManage unregistervm "omnetpp-vm" --delete || true
    # Create VM commands
    - VBoxManage --version
    - VBoxManage createvm --name "omnetpp-vm" --register
    - VBoxManage modifyvm "omnetpp-vm" --memory 4096 --cpus 2
    - VBoxManage createhd --filename "omnetpp-vm.vdi" --size 30000
    - VBoxManage storagectl "omnetpp-vm" --name "SATA Controller" --add sata --controller IntelAhci
    - VBoxManage storageattach "omnetpp-vm" --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "omnetpp-vm.vdi"
    - VBoxManage startvm "omnetpp-vm" --type headless
    - mkdir ./public_vm
    - cp ./omnetpp-vm.vdi ./public_vm
    
  after_script:
    # Cleanup VM commands
    - VBoxManage controlvm "omnetpp-vm" poweroff
    - VBoxManage unregistervm "omnetpp-vm" --delete
    
  artifacts:
    paths:
      - public_vm/omnetpp-vm.vdi
        
  tags:
    - d6g
    - shell

variables:
  IMAGE_TAG_OMNETPP_GUI_XVFB: $CI_REGISTRY_IMAGE:omnetpp-gui-xvfb-latest
  # Tell 'docker:dind' to enable TLS (recommended)
  # and generate certificates in the specified directory.
  DOCKER_TLS_CERTDIR: "/certs"

# Disable for now until docker registry is enabled
#build-docker-omnetpp-gui-xvfb:
#  stage: docker-base
#  rules:
#    - changes:
#        - dockerfiles/omnetpp-gui-xvfb/*
#        - .gitlab-ci.yml
#  image: docker:latest
#  services:
#    - docker:dind
#  script:
#    - cd dockerfiles/omnetpp-gui-xvfb
#    - echo $CI_REGISTRY
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker build -t $IMAGE_TAG_OMNETPP_GUI_XVFB .
#    - docker push $IMAGE_TAG_OMNETPP_GUI_XVFB
#  tags:
#    - d6g
#    - docker


build-doc:
  only:
    - documentation
    - main
  stage: build
  script:
    - (cd ..; git clone --depth 1 --branch v4.5.0 https://github.com/inet-framework/inet.git;)
    - xvfb-run make doc
  after_script:
    - rm -rf ../inet
  artifacts:
    paths:
      - public
  tags:
    - d6g
    - shell


publish-pages:
  stage: deploy
  only:
    - disabled
  artifacts:
    paths:
      - public
  script:
    - echo "Publishing to $CI_PAGES_URL"

