stages:
  - build
  - deploy

variables:
  IMAGE_TAG_OMNETPP_GUI_XVFB: $CI_REGISTRY_IMAGE:omnetpp-gui-xvfb-latest
  # Tell 'docker:dind' to enable TLS (recommended)
  # and generate certificates in the specified directory.
  DOCKER_TLS_CERTDIR: "/certs"

pages:
  only:
    - develop
  stage: build
  script:
    - (cd ..; git clone --depth 1 --branch v4.5.0 https://github.com/inet-framework/inet.git;)
    - xvfb-run make doc
  after_script:
    - rm -rf ../inet
  artifacts:
    paths:
      - public
  tags:
    - d6g
    - shell

deploy_ipvs_pages:
  variables:
    DEPLOYMENT_PATH: /mnt/www_d6g/$CI_PROJECT_PATH
  stage: deploy
  dependencies:
    - pages
  environment:
    name: production
    url: "https://ipvs.informatik.uni-stuttgart.de/vs/deterministic6g/$CI_PROJECT_PATH"
  only:
    - develop
  script:
    - rm -rf $DEPLOYMENT_PATH || true
    - mkdir -p $DEPLOYMENT_PATH
    - cp -r public/. $DEPLOYMENT_PATH
  tags:
    - d6g
    - docker
    - web
