stages:
  - docker-base
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  # Tell 'docker:dind' to enable TLS (recommended)
  # and generate certificates in the specified directory.
  DOCKER_TLS_CERTDIR: "/certs"

build-docker-omnetpp-gui-xvfb:
  stage: docker-base
  rules:
    - changes:
        - dockerfiles/omnetpp-gui-xvfb/*
  image: docker:latest
  # Specify an additional image 'docker:dind' ("Docker-in-Docker") that
  # will start up the Docker daemon when it is brought up by a runner.
  services:
    - name: $CI_REGISTRY/group/project/docker:20.10.16-dind
      alias: docker
  script:
    - cd
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG


build-docker:
  only:
    - disabled
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

build-doc:
  only:
    - disabled
  image: ghcr.io/omnetpp/omnetpp-gui:u22.05-6.0.1
  stage: build
  script:
    - ls
    - ls ..
    - pwd
    - (cd ..; git clone --depth 1 --branch v4.5.0 https://github.com/inet-framework/inet.git;)
    - ls ..
    - make neddoc
    - ls doc

publish-pages:
  stage: deploy
  only:
    - main
    - documentation
  artifacts:
    paths:
      - public
  script:
    - echo "Publishing to $CI_PAGES_URL"