stages:
  - docker-base
  - build
  - deploy

variables:
  IMAGE_TAG_OMNETPP_GUI_XVFB: $CI_REGISTRY_IMAGE:omnetpp-gui-xvfb-latest
  # Tell 'docker:dind' to enable TLS (recommended)
  # and generate certificates in the specified directory.
  DOCKER_TLS_CERTDIR: "/certs"

build-docker-omnetpp-gui-xvfb:
  stage: docker-base
  rules:
    - changes:
        - dockerfiles/omnetpp-gui-xvfb/*
        - .gitlab-ci.yml
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd dockerfiles/omnetpp-gui-xvfb
    - echo $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG_OMNETPP_GUI_XVFB .
    - docker push $IMAGE_TAG_OMNETPP_GUI_XVFB


build-docker:
  only:
    - disabled
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

build-doc:
  only:
    - documentation
    - main
  image: $IMAGE_TAG_OMNETPP_GUI_XVFB
  stage: build
  script:
    - ls
    - ls ..
    - pwd
    - (cd ..; git clone --depth 1 --branch v4.5.0 https://github.com/inet-framework/inet.git;)
    - ls ..
    - make neddoc
    - ls public
    - rm -rf ../inet
  artifacts:
    paths:
      - public

publish-pages:
  stage: deploy
  only:
    - disabled
  artifacts:
    paths:
      - public
  script:
    - echo "Publishing to $CI_PAGES_URL"