on:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  fingerprint_test:
    name: "Fingerprint Test"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/omnetpp/omnetpp:u22.04-6.0.1
      options: --user root
    steps:
      - name: Checkout Deterministic6G repository
        uses: actions/checkout@main
        with:
          path: deterministic6g
      - name: Checkout INET repository
        uses: actions/checkout@main
        with:
          repository: inet-framework/inet
          path: inet
          ref: 'v4.5.2'
      - name: "Run fingerprint test"
        shell: bash
        run: |
          source "/root/omnetpp/setenv"
          which omnetpp
          echo $PATH
          cd inet
          source setenv
          make makefiles
          make -j$(nproc)
          cd ../deterministic6g
          make makefiles
          make
          cd tests/fingerprint
          inet_fingerprinttest
