on:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  fingerprint_test:
    name: "Fingerprint Test"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/omnetpp/omnetpp:u22.04-6.0.1
      options: --user root
    steps:
      - name: Checkout Deterministic6G repository
        uses: actions/checkout@main
        with:
          path: deterministic6g
      - name: Checkout deterministic6g_data repository
        uses: actions/checkout@main
        with:
          repository: DETERMINISTIC6G/deterministic6g_data
          path: deterministic6g_data
      - name: Download data for tests
        run: |
          cd deterministic6g_data/PD-Wireless-5G-1
          pip install requests pyarrow
          export PYTHONPATH=$PYTHONPATH:..
          python3 main.py
      - name: Checkout INET repository
        uses: actions/checkout@main
        with:
          repository: inet-framework/inet
          path: inet
          ref: 'v4.5.2'
      - name: Cache INET build
        uses: actions/cache@v2
        with:
          path: |
            inet/out
            inet/.cache
          key: ${{ runner.os }}-inet-${{ hashFiles('inet/**') }}
          restore-keys: |
            ${{ runner.os }}-inet-
      - name: "Run fingerprint test"
        shell: bash
        run: |
          source "/root/omnetpp/setenv"
          which omnetpp
          echo $PATH
          cd inet
          source setenv
          make makefiles
          make -j$(nproc)
          cd ../deterministic6g
          make makefiles
          make
          cd tests/fingerprint
          inet_fingerprinttest
