on:
  push:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  fingerprint_test:
    name: "Fingerprint Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout deterministic6g repo"
        uses: actions/checkout@main
      - name: "Checkout inet repo"
        uses: actions/checkout@main
        with:
          repository: inet-framework/inet
          path: inet
          ref: 'v4.5.2'
      - name: "Run fingerprint test"
        uses: docker://ghcr.io/omnetpp/omnetpp:u22.04-6.0.1
        run: |
          which omnetpp
          echo $PATH
          cd inet
          source setenv
          make makefiles
          make -j$(nproc)
          cd ../deterministic6g
          make makefiles
          make
          cd tests/fingerprint
          inet_fingerprinttest
